FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install @vitejs/plugin-react --save-dev

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]